In [ ]:
# -*- coding: utf-8 -*-
# Indentation: Jupyter Notebook

'''
ANN for Churn Prediction
'''

__version__ = 1.0
__author__ = "Sourav Raj"
__author_email__ = "souravraj.iitbbs@gmail.com"


In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
data = pd.read_csv('../data/Churn_Modelling.csv')

In [4]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X=data.iloc[:,3:13].values
y=data.iloc[:,13].values

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1]= labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:, 2]= labelencoder_X_2.fit_transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

C:\Users\sourav.raj\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\sourav.raj\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [7]:
X=X[:, 1:]

In [8]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# ANN
import keras 
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [12]:
# initializing the ANN
classifier = Sequential()

In [13]:
# adding the input layer & first hidden layer
classifier.add(Dense(output_dim=6, init= 'uniform', activation = 'relu', input_dim = 11))

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


C:\Users\sourav.raj\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [14]:
# adding the 2nd hidden layer
classifier.add(Dense(output_dim=6, init= 'uniform', activation = 'relu'))

C:\Users\sourav.raj\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [15]:
# adding the output layer
classifier.add(Dense(output_dim=1, init= 'uniform', activation = 'sigmoid'))

C:\Users\sourav.raj\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [16]:
# compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics =['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [17]:
# fitting the ANN to training set
classifier.fit(X_train, y_train, batch_size=10, nb_epoch=5 )

C:\Users\sourav.raj\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  



Epoch 1/5
8000/8000 [==============================] - 2s 219us/step - loss: 0.5059 - accuracy: 0.7954
Epoch 2/5
8000/8000 [==============================] - 1s 175us/step - loss: 0.4128 - accuracy: 0.8091
Epoch 3/5
8000/8000 [==============================] - 1s 175us/step - loss: 0.3873 - accuracy: 0.8259
Epoch 4/5
8000/8000 [==============================] - 1s 172us/step - loss: 0.3674 - accuracy: 0.8496
Epoch 5/5
8000/8000 [==============================] - 2s 206us/step - loss: 0.3571 - accuracy: 0.8553


In [18]:
y_pred = classifier.predict(X_test)

In [19]:
y_pred[1:10]

array([[0.37661898],
       [0.2101087 ],
       [0.09235263],
       [0.05955303],
       [0.7783611 ],
       [0.03829879],
       [0.06776088],
       [0.26318502],
       [0.7801693 ]], dtype=float32)

In [20]:
y_pred = (y_pred > 0.50)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [21]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0, 600, 1, 40, 3, 6000,2, 1,1, 50000]])))

In [22]:
new_prediction = (new_prediction > 0.50)
new_prediction

array([[False]])

In [23]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [24]:
cm

array([[1529,   66],
       [ 204,  201]], dtype=int64)

In [27]:
(cm[0][0] + cm[1][1] )/cm.sum()

0.865

2000