In [ ]:
# -*- coding: utf-8 -*-
# Indentation: Jupyter Notebook

'''
ANN for Churn Prediction
'''

__version__ = 1.0
__author__ = "Sourav Raj"
__author_email__ = "souravraj.iitbbs@gmail.com"


In [1]:
import tensorflow as tf

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
data = pd.read_csv('../data/Churn_Modelling.csv')

In [4]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [5]:
X=data.iloc[:,3:13].values
y=data.iloc[:,13].values

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1]= labelencoder_X_1.fit_transform(X[:,1])
labelencoder_X_2 = LabelEncoder()
X[:, 2]= labelencoder_X_2.fit_transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()

In [7]:
X=X[:, 1:]

In [8]:
X

array([[  0.00000000e+00,   0.00000000e+00,   6.19000000e+02, ...,
          1.00000000e+00,   1.00000000e+00,   1.01348880e+05],
       [  0.00000000e+00,   1.00000000e+00,   6.08000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   1.12542580e+05],
       [  0.00000000e+00,   0.00000000e+00,   5.02000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   1.13931570e+05],
       ..., 
       [  0.00000000e+00,   0.00000000e+00,   7.09000000e+02, ...,
          0.00000000e+00,   1.00000000e+00,   4.20855800e+04],
       [  1.00000000e+00,   0.00000000e+00,   7.72000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   9.28885200e+04],
       [  0.00000000e+00,   0.00000000e+00,   7.92000000e+02, ...,
          1.00000000e+00,   0.00000000e+00,   3.81907800e+04]])

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
# ANN
import keras 
from keras.models import Sequential
from keras.layers import Dense


Using TensorFlow backend.


In [12]:
# initializing the ANN
classifier = Sequential()

In [13]:
# adding the input layer & first hidden layer
classifier.add(Dense(output_dim=6, init= 'uniform', activation = 'relu', input_dim = 11))

C:\Users\sourav.raj.IN\AppData\Local\conda\conda\envs\python36\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=11, units=6, kernel_initializer="uniform")`
  


In [14]:
# adding the 2nd hidden layer
classifier.add(Dense(output_dim=6, init= 'uniform', activation = 'relu'))

C:\Users\sourav.raj.IN\AppData\Local\conda\conda\envs\python36\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="uniform")`
  


In [15]:
# adding the output layer
classifier.add(Dense(output_dim=1, init= 'uniform', activation = 'sigmoid'))

C:\Users\sourav.raj.IN\AppData\Local\conda\conda\envs\python36\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
  


In [16]:
# compiling the ANN
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics =['accuracy'])

In [17]:
# fitting the ANN to training set
classifier.fit(X_train, y_train, batch_size=10, nb_epoch=100 )

C:\Users\sourav.raj.IN\AppData\Local\conda\conda\envs\python36\lib\site-packages\keras\models.py:942: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


Epoch 1/100
8000/8000 [==============================] - 4s 469us/step - loss: 0.4885 - acc: 0.7955

In [18]:
y_pred = classifier.predict(X_test)

In [19]:
y_pred[1:10]

array([[ 0.33631179],
       [ 0.18487103],
       [ 0.06216956],
       [ 0.16657516],
       [ 0.85727119],
       [ 0.06694856],
       [ 0.07193249],
       [ 0.1100153 ],
       [ 0.87042791]], dtype=float32)

In [20]:
y_pred = (y_pred > 0.50)
y_pred

array([[False],
       [False],
       [False],
       ..., 
       [False],
       [False],
       [False]], dtype=bool)

In [ ]:
new_prediction = classifier.predict(sc.transform(np.array([[0,0, 600, 1, 40, 3, 6000,2, 1,1, 50000]])))

In [ ]:
new_prediction = (new_prediction > 0.50)
new_prediction

In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [22]:
cm

array([[1543,   52],
       [ 266,  139]], dtype=int64)

In [23]:
(1549 +133 )/2000

0.841